name: CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Tests
      run: |
        cd /home/runner/work/Project_0AD/Project_0AD/binaries/system
        ./test.exe
